# Generated by Django 4.0 on 2022-01-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.CharField(editable=False, max_length=225, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='advertise_slider/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constitution',
            fields=[
                ('id', models.CharField(editable=False, max_length=225, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desingnation',
            fields=[
                ('id', models.CharField(editable=False, max_length=225, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('constitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.constitution')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.CharField(editable=False, max_length=225, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.CharField(editable=False, max_length=225, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('meta_desc', models.TextField(blank=True)),
                ('meta_keyword', models.TextField(blank=True)),
                ('desc', models.TextField()),
                ('profile', models.ImageField(upload_to='politician_profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('constitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.constitution')),
                ('desingnation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.desingnation')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.CharField(editable=False, max_length=225, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(editable=False, max_length=225, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[(1, 'Admin'), (2, 'Editor'), (3, 'User')], default=1, max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=225)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Politician_video_slider',
            fields=[
                ('id', models.CharField(editable=False, max_length=225, primary_key=True, serialize=False)),
                ('video', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.politician')),
            ],
        ),
        migrations.CreateModel(
            name='Politician_image_slider',
            fields=[
                ('id', models.CharField(editable=False, max_length=225, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='politician_imgage_slider/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.politician')),
            ],
        ),
        migrations.AddField(
            model_name='politician',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='politician',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.district'),
        ),
        migrations.AddField(
            model_name='politician',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='politician',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.state'),
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.CharField(editable=False, max_length=225, primary_key=True, serialize=False)),
                ('text', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.state'),
        ),
        migrations.AddField(
            model_name='desingnation',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.district'),
        ),
        migrations.AddField(
            model_name='desingnation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.state'),
        ),
        migrations.AddField(
            model_name='constitution',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.district'),
        ),
        migrations.AddField(
            model_name='constitution',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.state'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(editable=False, max_length=225, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='comment_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.customuser')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.politician')),
            ],
        ),
    ]
