# Generated by Django 4.0 on 2022-04-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_politician_party_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Editor'), (3, 'User')], default=3, max_length=10),
        ),
    ]
